#!/usr/bin/env ruby
# ^ vim filetype detection assist

forge 'https://forge.puppetlabs.com'

mod 'puppetlabs/apache'
mod 'puppetlabs/ntp'
mod 'puppetlabs/java'
mod 'puppetlabs/stdlib'
mod 'puppetlabs/ruby'
mod 'puppetlabs/gcc'
mod 'puppetlabs/git'
mod 'puppetlabs/concat'
mod 'puppetlabs/vcsrepo'
mod 'puppetlabs/apt'
mod 'puppetlabs/inifile'
mod 'puppetlabs/pe_gem'

mod 'zack/r10k'
mod 'tampakrap/hiera'
mod 'maestrodev/wget'
mod 'stahnma/epel'
mod 'nanliu/staging'
mod 'puppet/virtualbox'
mod 'counsyl/sys'
mod 'counsyl/packer'
mod 'jdowning/rbenv'
mod 'garethr/docker'
mod 'camptocamp/archive'
mod 'croddy/make'
mod 'gentoo/portage'
mod 'ploperations/puppet'
